#!/usr/bin/env python3

from sys       import argv
from itertools import takewhile
from os        import execv

# Usage: `./kink <kink-args> -- <k-args>`
# 
# See src/command-line.md for details
# 
# e.g. `./kink kompile         -- definition.k`
# e.g. `./kink kast    pgm.foo -- foo.k`

args = iter(argv)
next(args)
kink_args = takewhile(lambda arg: arg != '--', args)
k_args = args

command = [ './build', '--' # Need k-light in PATH
          , 'opam', 'config', 'exec', '--'
          , 'ext/k/k-distribution/target/release/k/bin/krun'
          , '--directory', '.build/kink'
          , "-cCOMMANDLINE=%s" %(' '.join(list(kink_args)))
          , *k_args
          ]
execv ('./build', command)
