#!/usr/bin/env python3

import sys
import string
import re

# Usage: k-from-config <input> <output>
in_file = sys.argv[1]
out_file = sys.argv[2]

def remove_prefix(text, prefix):
    if text.startswith(prefix):
        return text[len(prefix):]
    return text

input = open(in_file).read()
open_tag = '<k>'
close_tag = '</k>'

begin = re.search(open_tag, input)
end   = re.search(close_tag, input)
kore = input[begin.end():end.start()]

# Remove unwanted units from Lists etc.
commaSeparated = ['AttrList', 'KoreNames', 'Names',  'Patterns', 'Sorts']
others = ['Modules', 'Declarations', 'KImportList', 'TagContents']
for listSort in commaSeparated:
    kore = kore.replace(' , .' + listSort, '')
for listSort in commaSeparated + others:
    kore = kore.replace('.'   + listSort, '')

outfile = open(out_file, 'w')
for line in kore.split("\n")[1:-1]:
    prefix = "  "
    print(remove_prefix(line, prefix).rstrip(), file = outfile)
