#!/usr/bin/env python3
# Usage: kink-kompile <definition.k> <krun-args>

import subprocess
import sys

definition_k = sys.argv[1]
k_args = sys.argv[2:]

subprocess.check_call(['./build', 'kink'])
subprocess.check_call(['./build', '--'
                      , 'opam', 'config', 'exec', '--'
                      , 'ext/k/k-distribution/target/release/k/bin/krun'
                      , '--directory', '.build/kink'
                      , '-cPIPELINE=#ekorePipeline'
                      , definition_k
                      , *k_args
                      ]
                     )
