#!/usr/bin/env python3
# Usage: kink-kast <definition.k> <program> <krun-args>

import subprocess
import sys

definition_k = sys.argv[1]
program = sys.argv[2]
k_args = sys.argv[3:]

subprocess.check_call(['./build', 'kink'])
subprocess.check_call(['./build', '--'
                      , 'opam', 'config', 'exec', '--'
                      , 'ext/k/k-distribution/target/release/k/bin/krun'
                      , '--directory', '.build/kink'
                      , '-cPIPELINE=#kastPipeline("' + program + '")'
                      , definition_k
                      , *k_args
                      ])
