#!/usr/bin/env python3

commaSeparated = ['Sorts', 'Names']
others = ['Modules', 'Patterns', 'Declarations']

import sys
import string
import re

def remove_prefix(text, prefix):
    if text.startswith(prefix):
        return text[len(prefix):]
    return text

# Remove unwanted units from Lists etc.
# =====================================

input = open(sys.argv[1]).read()
begin = re.search('<koreDefinition>', input)
end   = re.search('</koreDefinition>', input)

kore = input[begin.end():end.start()]
for listSort in commaSeparated:
    kore = kore.replace(' , .' + listSort, '')
for listSort in commaSeparated + others:
    kore = kore.replace('.'   + listSort, '')
outfile = open(sys.argv[2], 'w')
for line in kore.split("\n"):
    prefix = "    "
    print(remove_prefix(line, prefix), file = outfile)
